---
- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: ${params.txlatestbucket}
      aws_access_key: AKIAZOGSWYVYPJWUYV76
      aws_secret_key: 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
      policy: "{{ lookup( 'file','my_bucket_policy.json' )}}"
      state: present
      region: ${params.ap-south-1}
      versioning: no
      
